site_name: PyMDPs
site_author: Duncan Eddy
site_description: PyMDPs - Markov Decision Processes in Python
site_url: https://duncaneddy.github.io/pymdps/
repo_url: https://github.com/duncaneddy/pydmps
docs_dir: pages
use_directory_urls: false

extra_css:
    - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings
  - section-index
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
      fallback_to_build_date: true

theme:
  name: material
  logo: assets/logo-no-text.png
  favicon: assets/favicon-web.png
  highlightjs: true
  font:
    # text: Fira Mono
    code: Fira Mono
  hljs_languages:
    - yaml
    - rust
    - python
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom # Star-Trek Orange
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom # Star-Trek Orange
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
nav:
  - PyMDPs: index.md
  - Getting Started (Tutorials & Guides):
    - getting_started/index.md
    - getting_started/first_steps.md
  - API Reference:
    - api_reference/index.md
  - Reference:
    - reference/index.md
  - About:
    - about/index.md
    - about/contributing.md
    - about/alternatives.md
  - Author: https://duncaneddy.com

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.plot.ly/plotly-latest.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6