name: ci

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  unit-tests:
    uses: ./.github/workflows/tests.yml
  update-docs: 
    uses: ./.github/workflows/update-docs.yml