name: Publish Docs (Subworkflow)

on: [ workflow_call ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Update Pip
        run: python -m pip install --upgrade pip

      - name: Build Docs
        run: make docs

      - name: Deploy Docs
        run: |
          cd docs
          mkdocs gh-deploy --force