name: Publish docs
on: [ workflow_call ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update Pip
        run: python -m pip install --upgrade pip

      - name: Build Docs
        run: make docs

      - name: Deploy Docs
        run: mkdocs gh-deploy --force